name: Update contributions data

on:
  schedule:
    - cron: '0 3 * * *' # 3:00 UTC daily
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'scripts/fetch-contributions.mjs'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate contributions JSON
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_CONTRIBUTIONS_TOKEN }}
          GITHUB_USERNAME: ${{ vars.GITHUB_USERNAME || 'darraghmahns' }}
        run: node scripts/fetch-contributions.mjs

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/contributions.json
            git commit -m "chore: update contributions data"
            git push
          else
            echo "No changes to commit"
          fi

